name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Remove shallow
        run: git fetch --depth=10000

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build greeting-service with Maven
        run: mvn -B package docker:build docker:push --file ./greeting-service/pom.xml

      - name: Build calc-service with Maven
        run: mvn -B package docker:build docker:push --file ./calc-service/pom.xmlpom.xml
